### ISSUE TITLE
Wallpapers

### ISSUE THREAD

**Issue by orhnk** [bibjaw99/workstation#1]
That's fire!

![image](https://github.com/bibjaw99/workstation/assets/101834410/3a560d28-7eb0-4ddc-ab28-25bce6a52c58)

bro, am a gruvbox lover too! And you know color schemes doesn't always fit to your eye's needs (especially for wallpapers)

did you used a program like `gruvbox-factory` to generate them from the base image?

nvm I and humanity would appreciate if you'd give those beauties to us!

**Comment by bibjaw99** [comment]
> That's fire!
> 
> ![image](https://user-images.githubusercontent.com/101834410/263506669-3a560d28-7eb0-4ddc-ab28-25bce6a52c58.png)
> 
> bro, am a gruvbox lover too! And you know color schemes doesn't always fit to your eye's needs (especially for wallpapers)
> 
> did you used a program like `gruvbox-factory` to generate them from the base image?
> 
> nvm I and humanity would appreciate if you'd give those beauties to us!

I just used gimp after downloading that wall from wallhaven.

**Comment by orhnk** [comment]
> I just used gimp after downloading that wall from wallhaven.

That's cool!

But Where can I these wallpapers.

(all of them that you have in the README)

**Comment by orhnk** [comment]
For time travelers: 
GIMP: Hue Chroma is insane!!!
+ Color Enchance

**Comment by orhnk** [comment]
I didn't close this issue cuz I thought you'd send them
