### ISSUE TITLE
Uppercase is beaking polybar

### ISSUE THREAD

**Issue by holoisbestwaifu** [bibjaw99/workstation#3]
Hi, your dotfiles are created and i used them as base for my config and noticed that in ~/.config/polybar/colors.ini you have an uppercase letter which broke transparency of bar.
![image](https://github.com/bibjaw99/workstation/assets/169564053/27e03dd2-c981-4e12-9229-0d7d16c84590)

**Comment by bibjaw99** [comment]
> Hi, your dotfiles are created and i used them as base for my config and noticed that in ~/.config/polybar/colors.ini you have an uppercase letter which broke transparency of bar. ![image](https://private-user-images.githubusercontent.com/169564053/329817278-27e03dd2-c981-4e12-9229-0d7d16c84590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzEzNDcsIm5iZiI6MTcxNjE3MTA0NywicGF0aCI6Ii8xNjk1NjQwNTMvMzI5ODE3Mjc4LTI3ZTAzZGQyLWM5ODEtNGUxMi05MjI5LTBkN2QxNmM4NDU5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjEwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmZkMGE0MTZhMzIzNmIwMTgwZTI1NzhhNmZlOTE1MWY5MjM0NGMxYjg4OWM0MzM3YTk4Y2RmYTYzNzA5MjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iyehJDoA-aTYuX5ZBXmTW5RI5qkTI1rwTNRNloaQrQ0)

I don't understand why a uppercase variable name will cause a breakage !! As you can see mine is working fine ... but if it needs to be changed in your system then change it ...
![Uploading 2024-05-20_08-10.png…]()

**Comment by bibjaw99** [comment]
> Hi, your dotfiles are created and i used them as base for my config and noticed that in ~/.config/polybar/colors.ini you have an uppercase letter which broke transparency of bar. ![image](https://private-user-images.githubusercontent.com/169564053/329817278-27e03dd2-c981-4e12-9229-0d7d16c84590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzE3ODIsIm5iZiI6MTcxNjE3MTQ4MiwicGF0aCI6Ii8xNjk1NjQwNTMvMzI5ODE3Mjc4LTI3ZTAzZGQyLWM5ODEtNGUxMi05MjI5LTBkN2QxNmM4NDU5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMjE4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODRmYTkyODRmMDY2MTk3ODM3NjNiMTM0ZDdlMzIyZWQ3MGY0Y2ZhOTI3ZTcwMzNlYjgwMDU4NTI0ZjEwOTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rdy11MDDBnfBi-vG0ua35t1qk2RffFpYTULg6jTFUzk)

I don't understand why a uppercase variable name will cause a breakage !! As you can see mine is working fine ... but if it needs to be changed in your system then change it ...
![2024-05-20_08-10](https://github.com/bibjaw99/workstation/assets/134938208/fcb12578-32d7-4c78-a439-2188b93d8134)

**Comment by holoisbestwaifu** [comment]
You need to check colors.ini, not a config.ini :3

**Comment by bibjaw99** [comment]
> You need to check colors.ini, not a config.ini :3

i know .. I wrote it ... Again variables can be both in uppercase and lowercase... That is totally not an issue.
