### ISSUE TITLE
Do you use alacritty or kitty?

### ISSUE THREAD

**Issue by KomarPL** [bibjaw99/workstation#4]
In one of your commits i saw "[Kitty is the only terminal now since it's more consistent](https://github.com/bibjaw99/workstation/commit/3deade7d4f2888e7d944f832d08f03f7f75911a4)" but lately i have seen that you have changed sth in one of your alacritty config files.

**Comment by vidy007** [comment]
I use Alacritty because i dont want to wait 1sec for kitty to start

**Comment by bibjaw99** [comment]
> In one of your commits i saw "[Kitty is the only terminal now since it's more consistent](https://github.com/bibjaw99/workstation/commit/3deade7d4f2888e7d944f832d08f03f7f75911a4)" but lately i have seen that you have changed sth in one of your alacritty config files.

I was using alacritty the wrong way ... Kitty is nice but when I went back to alacritty again did some modifications , it seemed better. Specially font rendering is really nice in alacritty compared to kitty.

**Comment by bibjaw99** [comment]
You can just change your termianl ... I experiment with different stuff. It's just my home config , And many things depends on your machine and hardwares.
